name: Build and Deploy
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - name: Install
        run: npm i

      - name: Build
        run: |
          npm run build:lib
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/ngx-carousel-app
